### ISSUE TITLE
Exception when using multiple

### ISSUE THREAD

**Issue by ksmaingi** [miguelalarcos/xautocomplete#3]
Loving the work in this package so far :+1: 

However, I keep getting the following error:

> Exception in template helper: TypeError: Cannot read property 'lastName' of undefined
>     at Object.Template.xautocomplete.helpers.init (http://localhost:3000/packages/miguelalarcos_xautocomplete.js?9f4a6ed3a2d47dc5dc5ba3a7caa851d3712cdd97:204:18)

This is what I'm using in my template:
`{{> xautocomplete  xmultiple='true' formid='1' name='lastName' reference='Clients' valuefunction='valueClient'
     renderfunction='renderClients' call='clientsFind' callbackfunction='clientSuggestCallback'}}`

I've also tried it without the `reference`.

Looking at the code it's this line causing the problem:
`value=obj[atts.name]`

But I'm unclear on what `obj` might be and why it shows up as undefined in the console.

**Comment by miguelalarcos** [comment]
Hi @ksmaingi , thanks for your interest in this package.

obj is the object passed to init to setup the widget with initial value. Are you using iron:router? I need to see the template and the _data_ section of the iron:router if you are using it.

In my example this is something like:

``` coffee
class MyController extends RouteController
  waitOn: -> Meteor.subscribe 'bookById', '0'
  data: ->
    data: books.findOne()
```

``` html
{{#with this.data}}
    {{> xautocomplete formid='2' name='surname' settings='settings01'}}
...
```

**Comment by ksmaingi** [comment]
Hi @miguelalarcos, thanks for getting back to me quickly.

I am using iron:router, but I don't have a data section. My template is as follows:

```
<template name="addEventBody">
<div class="control-group">
    <label class="control-label" for="eventType">Type:</label>
    <div class="controls">
      {{> eventTypes }}
    </div>
</div>
<div class="control-group">
  <label class="control-label" for="client">Client:</label>
  <div class="controls">
    {{> xautocomplete  xmultiple='true' formid='1' name='lastName' reference='Clients' valuefunction='valueClient'
     renderfunction='renderClients' call='clientsFind' callbackfunction='clientSuggestCallback'}}
  </div>
</div>
<div class="control-group">
  <a href="#" class="btn btn-green" id="createClient">Create a new client</a>
</div>
<input type="hidden" id="clientEmailAddress" />
<input type="hidden" id="clientName" />
<input type="hidden" id="clientId" />
<input type="hidden" id="eventType" />
</template>
```

Thanks!

**Comment by miguelalarcos** [comment]
You need to pass an object with the data to populate in the widget at init. It can come from a _data_ section in `iron:router` or a helper in `Template.addEventBody.helpers`

In both cases is normal that you will have a

``` html
<template name="addEventBody">
    {{#with ...}}
...
```

Can I see more of your code? Do you have it in github?

**Comment by ksmaingi** [comment]
Thanks, that's fixed it!

I don't have the code in github unfortunately at the moment.

**Comment by miguelalarcos** [comment]
I'm glad to know it's working!  :)
